/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Sebastian
 */
public class frmCitas extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCitas
     */
    public frmCitas() {
        initComponents();
        setClosable(true);
        setIconifiable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnMostar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cbxPaciente = new javax.swing.JComboBox<>();
        txtHora = new javax.swing.JTextField();
        txtFechaCita = new javax.swing.JTextField();
        btnMostrarCitas = new javax.swing.JButton();
        btnGuardarCita = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 450, 120));

        btnMostar.setText("Mostrar Pacientes");
        getContentPane().add(btnMostar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 142, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar cita", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxPaciente.setBorder(javax.swing.BorderFactory.createTitledBorder("cbxPaciente"));
        jPanel1.add(cbxPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 129, 50));

        txtHora.setBorder(javax.swing.BorderFactory.createTitledBorder("Digitar hora"));
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 180, 50));

        txtFechaCita.setBorder(javax.swing.BorderFactory.createTitledBorder("Digitar fecha (dd/MM/yyy)"));
        jPanel1.add(txtFechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 180, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 450, 160));

        btnMostrarCitas.setText("Mostrar citas");
        btnMostrarCitas.addActionListener(this::btnMostrarCitasActionPerformed);
        getContentPane().add(btnMostrarCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 160, 40));

        btnGuardarCita.setText("Guardar");
        btnGuardarCita.addActionListener(this::btnGuardarCitaActionPerformed);
        getContentPane().add(btnGuardarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 160, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarCitasActionPerformed

    private void btnGuardarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarCitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuardarCita;
    public javax.swing.JButton btnMostar;
    public javax.swing.JButton btnMostrarCitas;
    public javax.swing.JComboBox<modelo.Paciente> cbxPaciente;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblDatos;
    public javax.swing.JTextField txtFechaCita;
    public javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
