/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Sebastian
 */
public class frmCitas extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCitas
     */
    public frmCitas() {
        initComponents();
        setClosable(true);
        setIconifiable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnMostar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cbxPaciente = new javax.swing.JComboBox<>();
        txtHora = new javax.swing.JTextField();
        txtFechaCita = new javax.swing.JTextField();
        btnGuardarCita = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnEditarCita = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCitas = new javax.swing.JTable();
        btnOrdenar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 430, 170));

        btnMostar.setText("Mostrar Pacientes");
        getContentPane().add(btnMostar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 150, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar cita", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxPaciente.setBorder(javax.swing.BorderFactory.createTitledBorder("cbxPaciente"));
        jPanel1.add(cbxPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 129, 50));

        txtHora.setBorder(javax.swing.BorderFactory.createTitledBorder("Digitar hora"));
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 180, 50));

        txtFechaCita.setBorder(javax.swing.BorderFactory.createTitledBorder("Digitar fecha (dd/MM/yyy)"));
        jPanel1.add(txtFechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 180, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 430, 150));

        btnGuardarCita.setText("Guardar");
        btnGuardarCita.addActionListener(this::btnGuardarCitaActionPerformed);
        getContentPane().add(btnGuardarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 110, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Datos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditarCita.setText("Editar");
        jPanel2.add(btnEditarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCitas);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 340, 320));

        btnOrdenar.setText("Ordenar Por");
        jPanel2.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 110, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 360, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarCitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEditarCita;
    public javax.swing.JButton btnGuardarCita;
    public javax.swing.JButton btnMostar;
    public javax.swing.JButton btnOrdenar;
    public javax.swing.JComboBox<modelo.Paciente> cbxPaciente;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tblCitas;
    public javax.swing.JTable tblDatos;
    public javax.swing.JTextField txtFechaCita;
    public javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
