package vista;

/**
 *
 * @author Sebastian
 */
public class frmEditarRegistro extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmEditarRegistro
     */
    public frmEditarRegistro() {
        initComponents();
        this.setClosable(true);
        this.setIconifiable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDatoEditar = new javax.swing.JTextField();
        cbxDatoEditar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosPaciente = new javax.swing.JTable();
        btnMostrarRegP = new javax.swing.JButton();
        btnEditarReg = new javax.swing.JButton();
        btnEliminarReg = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos a editar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDatoEditar.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite dato nuevo"));
        jPanel1.add(txtDatoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 150, 50));

        cbxDatoEditar.setBorder(javax.swing.BorderFactory.createTitledBorder("Dato a editar"));
        jPanel1.add(cbxDatoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 160, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 464, 110));

        tblDatosPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatosPaciente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 470, 254));

        btnMostrarRegP.setText("Mostrar");
        getContentPane().add(btnMostrarRegP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 110, 30));

        btnEditarReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        getContentPane().add(btnEditarReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 45, 34));

        btnEliminarReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        getContentPane().add(btnEliminarReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 45, 34));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEditarReg;
    public javax.swing.JButton btnEliminarReg;
    public javax.swing.JButton btnMostrarRegP;
    public javax.swing.JComboBox<String> cbxDatoEditar;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblDatosPaciente;
    public javax.swing.JTextField txtDatoEditar;
    // End of variables declaration//GEN-END:variables
}
