/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JDesktopPane;

/**
 *
 * @author Sebastian
 */
public class frmPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPrincipal.class.getName());

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    // 👇 MÉTODO PÚBLICO para acceder al escritorio
    public JDesktopPane getEscritorio() {
        return Escritorio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnFrmRegistrar = new javax.swing.JButton();
        btnFrmCitas = new javax.swing.JButton();
        btnFrmEditarRegistro = new javax.swing.JButton();
        Escritorio = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 170, 90));

        btnFrmRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar-user.png"))); // NOI18N
        btnFrmRegistrar.setText("Registrar Paciente");
        jPanel1.add(btnFrmRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 170, 80));

        btnFrmCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cita.png"))); // NOI18N
        btnFrmCitas.setText("Registrar Cita");
        jPanel1.add(btnFrmCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 80));

        btnFrmEditarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btnFrmEditarRegistro.setText("Editar Paciente");
        jPanel1.add(btnFrmEditarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 170, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 510));

        Escritorio.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(Escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 850, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane Escritorio;
    public javax.swing.JButton btnFrmCitas;
    public javax.swing.JButton btnFrmEditarRegistro;
    public javax.swing.JButton btnFrmRegistrar;
    public javax.swing.JButton btnSalir;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
